<?php

declare(strict_types=1);

function nrbgg_preprocess_node(array &$variables): void {
  $node_type = $variables['node']->getType();
  $variables['attributes']['class'][] = 'node--type--' . \Drupal\Component\Utility\Html::getClass($node_type);
  $variables['attributes']['class'][] = 'node--view-mode--' . \Drupal\Component\Utility\Html::getClass($variables['view_mode']);
}

function nrbgg_preprocess_field(array &$variables) {
  $element = $variables['element'];
  $variables['attributes']['class'][] = 'field';
  $variables['attributes']['class'][] = 'field--name-' . \Drupal\Component\Utility\Html::getClass($element['#field_name']);
  $variables['attributes']['class'][] = 'field--type-' . \Drupal\Component\Utility\Html::getClass($element['#field_type']);
  if (!empty($element['#label_display'])) {
    $variables['attributes']['class'][] = 'field--label-' . \Drupal\Component\Utility\Html::getClass($element['#label_display']);
  }
}
